### ISSUE TITLE
Competition

### ISSUE THREAD

**Issue by charlesfries** [Iluvatar/UWROV#2]
Unrelated to this repository, are you guys competing in MATE again this year? I'm interested in joining the team.

**Comment by ryanedwincox** [comment]
Hi Charles,

Yes we are in the process of building a new vehicle for MATE and would love
to have your help!  Come by our lab on any Tuesday or Thursday at 5:30, it
is in OCE118 which is on the water right behind the south campus center.

Ryan

**Comment by charlesfries** [comment]
Ryan,

Awesome sounds great. BTW I was the guy on the Jesuit team who grabbed your number after the competition last year. My strong suit is software so if you need another software developer, I’m your guy. I’ll see ya tomorrow!
- CF

**Comment by ryanedwincox** [comment]
I thought that might be you.  Yeah I'm sure we will have plenty of work for
you to do.

See you tomorrow,
Ryan
